#!/usr/bin/env python
# -*- coding: UTF-8 -*-
import sys
import re


str = '''
{
    "originalDnis":"msml",
    "userData":"1530866619-57568|121430035",
    "speechSkillId":"4443",
    "callee":"605510060",
    "taskDataId":0,
    "callUUID":"00VR5J7PHGDGVF3B345H7B5AES05SCOU",
    "interactions":[
        {
            "hits":[

            ],
            "nodeName":"1、身份核实",
            "output":"您好，我是中国太平客服专员小慧，请问是[se0]欧阳娜纳女士吗？",
            "input":"",
            "questionId":"f3f1a97e-56d0-4775-af2d-4fcb4bf28c6b",
            "role":"robot",
            "contentId":"76gOgin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_05a50",
            "seq":3
        },
        {
            "hits":[
                {
                    "answerId":"1cbe8552-ee4e-44b1-9787-c236949fe362",
                    "hit":"是本人",
                    "pick":"true"
                }
            ],
            "nodeName":"1、身份核实",
            "output":"您好，我是中国太平客服专员小慧，请问是[se0]欧阳娜纳女士吗？",
            "input":"是的",
            "questionId":"f3f1a97e-56d0-4775-af2d-4fcb4bf28c6b",
            "role":"customer",
            "contentId":"76gOgin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_05a50",
            "seq":4
        },
        {
            "hits":[

            ],
            "nodeName":"3、说明来意",
            "output":"是这样，感谢您购买我公司的车险，现在想耽误您1分钟时间对您做一个简短的电话回访，您看可以吗？",
            "input":"",
            "questionId":"df754e7f-ffb8-4358-bc82-138d40933e19",
            "role":"robot",
            "contentId":"76gOqin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_0e8b5",
            "seq":5
        },
        {
            "hits":[
                {
                    "answerId":"a0bd5b46-44b9-477e-ac42-444183173c68",
                    "hit":"可以",
                    "pick":"true"
                }
            ],
            "nodeName":"3、说明来意",
            "output":"是这样，感谢您购买我公司的车险，现在想耽误您1分钟时间对您做一个简短的电话回访，您看可以吗？",
            "input":"可以",
            "questionId":"df754e7f-ffb8-4358-bc82-138d40933e19",
            "role":"customer",
            "contentId":"76gOqin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_0e8b5",
            "seq":6
        },
        {
            "hits":[

            ],
            "nodeName":"5、出生月份核对",
            "output":"为了维护您的权益，本次通话将会被录音。首先跟您确认一下您的个人信息，请问您身份证的出生年月是一九八六年几月呢？",
            "input":"",
            "questionId":"ede36e6d-9291-4c68-a87f-49b8cfbf5f40",
            "role":"robot",
            "contentId":"76gODin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_a8f20",
            "seq":7
        },
        {
            "hits":[
                {
                    "answerId":"22747855-508d-4a66-b6cd-d612f674b585",
                    "hit":"正确",
                    "pick":"true"
                }
            ],
            "nodeName":"5、出生月份核对",
            "output":"为了维护您的权益，本次通话将会被录音。首先跟您确认一下您的个人信息，请问您身份证的出生年月是一九八六年几月呢？",
            "input":"五月",
            "questionId":"ede36e6d-9291-4c68-a87f-49b8cfbf5f40",
            "role":"customer",
            "contentId":"76gODin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_a8f20",
            "seq":8
        },
        {
            "hits":[

            ],
            "nodeName":"8、条款及责任免除",
            "output":"好的，请问您是否看过保险条款，对于保险责任与责任免除部分都清楚了吗？",
            "input":"",
            "questionId":"4bb84142-0aa5-4f85-879d-eb4bcc5cf55a",
            "role":"robot",
            "contentId":"76gONin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_dfae5",
            "seq":9
        },
        {
            "hits":[

            ],
            "nodeName":"8、条款及责任免除",
            "output":"好的，请问您是否看过保险条款，对于保险责任与责任免除部分都清楚了吗？",
            "input":"呃",
            "questionId":"4bb84142-0aa5-4f85-879d-eb4bcc5cf55a",
            "role":"customer",
            "contentId":"76gONin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_dfae5",
            "seq":10
        },
        {
            "hits":[

            ],
            "nodeName":"8、条款及责任免除",
            "output":"请问您是否看过保险条款，对于保险责任与责任免除部分都清楚了吗？",
            "input":"",
            "questionId":"4bb84142-0aa5-4f85-879d-eb4bcc5cf55a",
            "role":"robot",
            "contentId":"76gOQin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_dfae5",
            "seq":11
        },
        {
            "hits":[
                {
                    "answerId":"175db606-d829-4573-a6db-638a2dab8cd9",
                    "hit":"清楚",
                    "pick":"true"
                }
            ],
            "nodeName":"8、条款及责任免除",
            "output":"请问您是否看过保险条款，对于保险责任与责任免除部分都清楚了吗？",
            "input":"对",
            "questionId":"4bb84142-0aa5-4f85-879d-eb4bcc5cf55a",
            "role":"customer",
            "contentId":"76gOQin008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_dfae5",
            "seq":12
        },
        {
            "hits":[

            ],
            "nodeName":"11、满意度评价",
            "output":"请问您对我司销售人员的服务满意吗？",
            "input":"",
            "questionId":"bbe68784-d55c-4f2a-8c98-9845f51b5b1f",
            "role":"robot",
            "contentId":"76gP4in008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_fd8bd",
            "seq":13
        },
        {
            "hits":[
                {
                    "answerId":"c547766e-96da-4f84-9db8-8e8d20025846",
                    "hit":"满意",
                    "pick":"true"
                }
            ],
            "nodeName":"11、满意度评价",
            "output":"请问您对我司销售人员的服务满意吗？",
            "input":"还可以",
            "questionId":"bbe68784-d55c-4f2a-8c98-9845f51b5b1f",
            "role":"customer",
            "contentId":"76gP4in008",
            "nodeType":"NormalNode",
            "nodeId":"word_node_fd8bd",
            "seq":14
        },
        {
            "hits":[

            ],
            "nodeName":"满意度评价1",
            "output":"感谢您选择太平财险，若有任何服务需求欢迎拨打服务电话95589。祝您幸福太平！最后请您为我的服务做个评价，请您打开拨号键盘，非常满意请按1，满意请按2、不满意请按7，非常不满意请按8。",
            "input":"",
            "questionId":"c34982e3-1f56-4a8d-ab8a-d1d73149a77b",
            "role":"robot",
            "contentId":"2",
            "nodeType":"KeyNavigationNode",
            "nodeId":"word_node_d4304",
            "seq":15
        },
        {
            "hits":[
                {
                    "answerId":"7db74bc9-ec86-4d6d-96a1-6306a19ccc18",
                    "hit":"2",
                    "pick":"true"
                }
            ],
            "nodeName":"满意度评价1",
            "output":"感谢您选择太平财险，若有任何服务需求欢迎拨打服务电话95589。祝您幸福太平！最后请您为我的服务做个评价，请您打开拨号键盘，非常满意请按1，满意请按2、不满意请按7，非常不满意请按8。",
            "input":"2",
            "questionId":"c34982e3-1f56-4a8d-ab8a-d1d73149a77b",
            "role":"customer",
            "contentId":"2",
            "nodeType":"KeyNavigationNode",
            "nodeId":"word_node_d4304",
            "seq":16
        },
        {
            "hits":[

            ],
            "nodeName":"结束语4",
            "output":"您的评价已记录，谢谢您的支持，再见。",
            "input":"",
            "questionId":"7ffbe528-315e-4253-b98c-f7443d7f03b7",
            "role":"robot",
            "contentId":"",
            "nodeType":"EndNode",
            "nodeId":"word_node_3a9ac91a-",
            "seq":17
        },
        {
            "hits":[

            ],
            "nodeName":"结束语4",
            "output":"您的评价已记录，谢谢您的支持，再见。",
            "input":"",
            "questionId":"7ffbe528-315e-4253-b98c-f7443d7f03b7",
            "role":"customer",
            "contentId":"",
            "nodeType":"EndNode",
            "nodeId":"word_node_3a9ac91a-",
            "seq":18
        }
    ],
    "caller":"38139600",
    "startTime":1530867010986,
    "taskName":"车险新契约回访测试环境",
    "endTime":1530867096094,
    "mediaPath":"/record/2018/07/06/1530866619-57568121430035.wav",
    "event":99,
    "taskId":0,
    "direction":1,
    "originalAni":"38139600"
}
'''

p = re.compile(r'("questionId":.{1,40},)')
m = p.match(str)
print m.group(0)
if m:
    print m.group(0)
else:
    print 'no match'